apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secret-manager-poc
spec:
  provider: azure
  - secretName: akv-secrets
    data:
    - key: password
      objectName: mongo-root-password
    - key: username
      objectName: mongo-root-username
    type: Opaque
  parameters:
    tenantId: "9652d7c2-1ccf-4940-8151-4a92bd474ed0"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: "3309438c-503b-4b45-b6a9-e7b6db802a54"   
    keyvaultName: "kvcrdduatwesteurope001"        
    objects:  |
      array:
        - |
          objectName: mongo-root-username
          objectType: secret              
          objectVersion: ""               
        - |
          objectName: mongo-root-password
          objectType: secret
          objectVersion: ""
