# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: db
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "ccb03316-c385-4274-a945-4d10d6bf96ef"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "kvcrdduatwesteurope001"        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: mongo-root-username
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: mongo-root-password
          objectType: secret
          objectVersion: ""
    tenantId: "9652d7c2-1ccf-4940-8151-4a92bd474ed0"                 # The tenant ID of the key vault

